---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8

suites:
  - name: default
    run_list:
      - recipe[site-solrtypo3org::default]
    attributes:
    driver_config:
      network:
      - ["forwarded_port", {guest: 8080, host: 8080, auto_correct: true}]
